<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup>  <UserSecretsId>1b35e8e6-df2e-4275-b508-1e55ceb59573</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MrChip.MedLincePro.Business\MrChip.MedLincePro.Business.csproj" />
    <ProjectReference Include="..\MrChip.MedLincePro.Data\MrChip.MedLincePro.Data.csproj" />
  </ItemGroup>
</Project>
