using MrChip.MedLincePro.Business.Dtos.Adm;
using MrChip.MedLincePro.Business.Models.Adm;

namespace MrChip.MedLincePro.Business.Mapping;

public static class DtoToEntityExtensions
{
    public static Empresa ToEntity(this EmpresaDto dto) => new()
    {
        EmpresaId = dto.EmpresaId,
        RazaoSocial = dto.RazaoSocial,
        NomeFantasia = dto.NomeFantasia,
        Cnpj = dto.Cnpj,
        Email = dto.Email,
        TelefoneDdd = dto.TelefoneDdd,
        TelefoneNumero = dto.TelefoneNumero,
        ContatoNome = dto.ContatoNome,
        ContatoEmail = dto.ContatoEmail,
        ContatoTelefoneDdd = dto.ContatoTelefoneDdd,
        ContatoTelefoneNumero = dto.ContatoTelefoneNumero,
        Cep = dto.Cep,
        EnderecoComplemento = dto.EnderecoComplemento,
        EnderecoNumero = dto.EnderecoNumero,
        Cnes = dto.Cnes,
        EmpresaTipo = dto.EmpresaTipo,
        LogoEmpresaMaior = dto.LogoEmpresaMaior,
        LogoEmpresaMenor = dto.LogoEmpresaMenor,
        LogoSistemaMenor = dto.LogoSistemaMenor,
        LogoSistemaMaior = dto.LogoSistemaMaior,
        LayoutPagina = dto.LayoutPagina,
        UrlApi = dto.UrlApi,
        IntegraPlantao = dto.IntegraPlantao,
        AppPlantao = dto.AppPlantao,
        NumeroGuiaPrestador = dto.NumeroGuiaPrestador,
        TrabalhaLoteGrupos = dto.TrabalhaLoteGrupos,
        PercentualPIS = dto.PercentualPIS,
        PercentualCOFINS = dto.PercentualCOFINS,
        PercentualCSLL = dto.PercentualCSLL,
        PercentualIR = dto.PercentualIR,
        PercentualINSS = dto.PercentualINSS,
        PercentualISS = dto.PercentualISS,
        TaxaAdm = dto.TaxaAdm,
        PathArquivos = dto.PathArquivos,
        DataCadastro = dto.DataCadastro == default ? DateTime.UtcNow : dto.DataCadastro,
        Ativo = dto.Ativo
    };

    public static Bureau ToEntity(this BureauDto dto) => new()
    {
        BureauId = dto.BureauId,
        EmpresaId = dto.EmpresaId,
        Nome = dto.Nome,
        NomeResumido = dto.NomeResumido,
        CpfCnpj = dto.CpfCnpj,
        Contato = dto.Contato,
        Email = dto.Email,
        TelefoneFixo = dto.TelefoneFixo,
        TelefoneCel = dto.TelefoneCel,
        Cep = dto.Cep,
        EnderecoComplemento = dto.EnderecoComplemento,
        EnderecoNumero = dto.EnderecoNumero,
        DataCadastro = dto.DataCadastro == default ? DateTime.UtcNow : dto.DataCadastro,
        Ativo = dto.Ativo,
        ApiAcesso = dto.ApiAcesso == default ? DateTime.UtcNow : dto.ApiAcesso,
        ApiIp = dto.ApiIp,
        ApiAcessos = dto.ApiAcessos,
        ApiCulture = dto.ApiCulture,
        ApiCountry = dto.ApiCountry,
        Adm = dto.Adm,
        AcessoApi = dto.AcessoApi,
        PrazoInclusaoGuia = dto.PrazoInclusaoGuia
    };

    public static Profissional ToEntity(this ProfissionalDto dto) => new()
    {
        ProfissionalId = dto.ProfissionalId,
        EmpresaId = dto.EmpresaId,
        Nome = dto.Nome,
        Registro = dto.Registro,
        Cpf = dto.Cpf,
        DataCadastro = dto.DataCadastro == default ? DateTime.UtcNow : dto.DataCadastro,
        Ativo = dto.Ativo,
        ConselhoProfissionalCodigo = dto.ConselhoProfissionalCodigo,
        UnidadeFederacaoCodigo = dto.UnidadeFederacaoCodigo,
        CboCodigo = dto.CboCodigo,
        Email = dto.Email,
        Telefone = dto.Telefone,
        Cep = dto.Cep,
        EnderecoComplemento = dto.EnderecoComplemento,
        EnderecoNumero = dto.EnderecoNumero,
        PermiteAcessoAgenda = dto.PermiteAcessoAgenda,
        AcessoPlantao = dto.AcessoPlantao,
        ComissaoGlosas = dto.ComissaoGlosas,
        NumeroPis = dto.NumeroPis,
        CodigoGrauDeParticipacao = dto.CodigoGrauDeParticipacao,
        BancoCodigo = dto.BancoCodigo,
        BancoAgencia = dto.BancoAgencia,
        BancoConta = dto.BancoConta,
        TipoDeDocumento = dto.TipoDeDocumento
    };

    public static UnidadeHospitalar ToEntity(this UnidadeHospitalarDto dto) => new()
    {
        CodigoCnes = dto.CodigoCnes,
        Cnpj = dto.Cnpj,
        Nome = dto.Nome,
        UfCodigo = dto.UfCodigo,
        UfSigla = dto.UfSigla,
        Latitude = dto.Latitude,
        Longitude = dto.Longitude,
        Description = dto.Description,
        NomeReduzido = dto.NomeReduzido,
        Cidade = dto.Cidade,
        Uf = dto.Uf,
        Token = dto.Token,
        ContatoEmail = dto.ContatoEmail,
        ContatoNome = dto.ContatoNome,
        DataCadastro = dto.DataCadastro == default ? DateTime.UtcNow : dto.DataCadastro,
        Ativo = dto.Ativo
    };

    public static Operadora ToEntity(this OperadoraDto dto) => new()
    {
        OperadoraId = dto.OperadoraId,
        OperadoraModalidadeId = dto.OperadoraModalidadeId,
        RegistroAns = dto.RegistroAns,
        RazaoSocial = dto.RazaoSocial,
        NomeFantasia = dto.NomeFantasia,
        Cnpj = dto.Cnpj,
        CarteiraMin = dto.CarteiraMin,
        CarteiraMax = dto.CarteiraMax,
        WsEndpoint = dto.WsEndpoint,
        WsRetornaBeneficiario = dto.WsRetornaBeneficiario,
        CarteiraMask = dto.CarteiraMask,
        ElegibilidadeTipo = dto.ElegibilidadeTipo,
        Token = dto.Token,
        ContatoEmail = dto.ContatoEmail,
        ContatoNome = dto.ContatoNome,
        SenhaNumCharSadt = dto.SenhaNumCharSadt,
        SenhaCharHonorario = dto.SenhaCharHonorario,
        SenhaCharConsulta = dto.SenhaCharConsulta,
        DataCadastro = dto.DataCadastro == default ? DateTime.UtcNow : dto.DataCadastro,
        Ativo = dto.Ativo,
        EmpresaOperadora = dto.EmpresaOperadora?.ToEntity() ?? new EmpresaOperadora()
    };

    public static EmpresaOperadora ToEntity(this EmpresaOperadoraDto dto) => new()
    {
        EmpresaOperadoraId = dto.EmpresaOperadoraId,
        EmpresaId = dto.EmpresaId,
        OperadoraId = dto.OperadoraId,
        CodigoAuxiliar = dto.CodigoAuxiliar,
        CodigoNaOperadora = dto.CodigoNaOperadora,
        NumeroGuia = dto.NumeroGuia,
        NomeFantasia = dto.NomeFantasia,
        WsLogin = dto.WsLogin,
        WsSenha = dto.WsSenha,
        WsSequencia = dto.WsSequencia,
        WsHabilitado = dto.WsHabilitado,
        TrabalhaPlantao = dto.TrabalhaPlantao,
        FaturamentoTiss = dto.FaturamentoTiss,
        NumeroGuiaObrigatorio = dto.NumeroGuiaObrigatorio,
        NumeroGuiaEmpresaObrigatorio = dto.NumeroGuiaEmpresaObrigatorio,
        LiberadoParaAgendaMedica = dto.LiberadoParaAgendaMedica,
        AtendimentoUrgencia = dto.AtendimentoUrgencia,
        AcrescimoCriancaIdoso = dto.AcrescimoCriancaIdoso,
        AtendimentoHorarioEspecial = dto.AtendimentoHorarioEspecial,
        AtendimentoApartamento = dto.AtendimentoApartamento,
        SenhaGuiaObrigatorio = dto.SenhaGuiaObrigatorio,
        ValidacaoGuiaHabilitado = dto.ValidacaoGuiaHabilitado,
        LiberadoNovoFaturamento = dto.LiberadoNovoFaturamento,
        VersaoXmlEnvio = dto.VersaoXmlEnvio,
        TipoIdentificacaoNaOperadora = dto.TipoIdentificacaoNaOperadora,
        FaturamentoLiberadoBureau = dto.FaturamentoLiberadoBureau,
        CompetenciaAtiva = dto.CompetenciaAtiva,
        MaxGuiasLote = dto.MaxGuiasLote,
        AutorizadoConsulta = dto.AutorizadoConsulta,
        AutorizadoTeleConsulta = dto.AutorizadoTeleConsulta,
        ConsultaGuiaTipoId = dto.ConsultaGuiaTipoId,
        CobrancaSADTOrigem = dto.CobrancaSADTOrigem,
        CobrancaSADTSolicitante = dto.CobrancaSADTSolicitante,
        CobrancaSADTExecutante = dto.CobrancaSADTExecutante,
        CobrancaHonorarioOrigem = dto.CobrancaHonorarioOrigem,
        CobrancaHonorarioContratado = dto.CobrancaHonorarioContratado,
        CobrancaHonorarioExecutante = dto.CobrancaHonorarioExecutante,
        NumeroGuiaPrincipalObrigatorio = dto.NumeroGuiaPrincipalObrigatorio,
        CopiarGuia = dto.CopiarGuia,
        CarteiraObrigatoria = dto.CarteiraObrigatoria,
        ContratoParticular = dto.ContratoParticular,
        ConvenioPublico = dto.ConvenioPublico,
        WsMrChipUrl = dto.WsMrChipUrl,
        WsMrChipElegibilidade = dto.WsMrChipElegibilidade,
        CaraterDoAtendimentoPadrao = dto.CaraterDoAtendimentoPadrao,
        TipoAtendimentoPadrao = dto.TipoAtendimentoPadrao,
        RegimeAtendimentoPadrao = dto.RegimeAtendimentoPadrao,
        Checkin = dto.Checkin,
        Checkout = dto.Checkout,
        TrabalhaTecnica = dto.TrabalhaTecnica,
        TagNumeroGuiaPrestador = dto.TagNumeroGuiaPrestador,
        HorarioObrigatorioXml = dto.HorarioObrigatorioXml,
        FormaCalculoProcedimento = dto.FormaCalculoProcedimento,
        ModeloGuiaAuxiliar = dto.ModeloGuiaAuxiliar,
        ConcatenarGrupoProcedimento = dto.ConcatenarGrupoProcedimento,
        DataCadastro = dto.DataCadastro == default ? DateTime.UtcNow : dto.DataCadastro,
        Ativo = dto.Ativo
    };
}
